apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: member-board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-2.amazonaws.com/st7/fastapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "DB_HOST_VALUE"
        - name: DB_USER
          value: "DB_USER_VALUE"
        - name: DB_PASS
          value: "DB_PASS_VALUE"
        - name: DB_NAME
          value: "DB_NAME_VALUE"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: member-board
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: member-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: <AWS_ACCOUNT_ID>.dkr.ecr.ap-south-2.amazonaws.com/st7/nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: member-board
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sy-ingress
  namespace: member-board
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: "project-group"
    alb.ingress.kubernetes.io/tags: "Name=Integrated-ALB,Project=Cloud-Board,Owner=st7"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: "ACM_ARN_VALUE"
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
    - host: "www.sy99.cloud"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /board
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
          - path: /management
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80