server {
    listen 80;
    server_name www.sy99.cloud;

    # 1. 메인 홈페이지 (VPC1: index.html)
    # Pod 내부의 로컬 파일을 보여주는 것이라 문제 없습니다.
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. 소영님의 게시판 기능 (EKS VPC2: /board)
    location /board/ {
        # ALB 주소가 나오기 전까지는 주석 처리하거나 
        # 임시로 localhost를 바라보게 하여 Nginx 실행 에러를 방지합니다.
        # proxy_pass http://<소영님_VPC2_EKS_ALB_주소>:8000; 
        proxy_pass http://127.0.0.1:8000; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. 유승님의 회원 관리 기능 (EKS VPC2: /management)
    location /management/ {
        # 마찬가지로 주석 처리하여 업스트림 에러를 방지합니다.
        # proxy_pass http://<유승님_VPC3_주소>;
        proxy_pass http://127.0.0.1:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}