server {
    listen 80;
    server_name www.sy99.cloud;

    # 1. 메인 홈페이지 (VPC1: index.html)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. 소영님의 게시판 기능 (EKS VPC2: /board)
    location /board/ {
        proxy_pass http://<소영님_VPC2_EKS_ALB_주소>:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. 유승님의 회원 관리 기능 (EKS VPC2: /management)
    location /management/ {
        # 피어링을 통해 접근 가능한 유승님의 내부 로드밸런서나 서버 IP
        proxy_pass http://<유승님_VPC3_주소>;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}